discussion/urls.py
from django.urls import path

from . import views

app_name = 'discussion'

urlpatterns = [
    path('', views.index, name='index'),
    path('newpost/', views.new_post, name='new_post'),
    path('<slug:post>/', views.post_single, name='post_single'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('penggunaan-masker/', views.penggunaan_masker, name='masker'),
    path('tips-trick/', views.tips_trick, name='tips-trick'),
    path('getTipsTrick/', views.getTipsTrick, name='getTipsTrick')
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('logging_in/', views.logging_in, name='logging_in'),
    path('logout/', views.logging_out, name='logging_out'),
    path('profiles/', views.profiles, name='profiles'),
    path('story/', views.story, name='story'),
    path('getStory/<str:name>', views.getStory, name='getStory')
]

tk1_ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('donasi/', include("donasi.urls")),
    path('discussion/', include("discussion.urls")),
    path('account/', include("login.urls")),
    path('news/', include("news.urls")),
]

discussion/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey

class Post(models.Model):

    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter(status='published')

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250, unique=True)
    excerpt = models.TextField(null=True)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    author = models.CharField(max_length=50)
    content = models.TextField()
    status = models.CharField(max_length=10, choices=options, default='published')
    objects = models.Manager()  # default manager
    newmanager = NewManager()  # custom manager

    def get_absolute_url(self):
        return reverse('discussion:post_single', args=[self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(MPTTModel):

    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')
    content = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['publish']

    def __str__(self):
        return self.name

discussion/forms.py
from django import forms
from .models import Comment, Post
from mptt.forms import TreeNodeChoiceField


class NewCommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comment
        fields = ('parent', 'content')

        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control mb-3', 'placeholder': 'Content'}),
        }

        labels = {
            'content': 'Content',
        }

    def save(self, *args, **kwargs):
        Comment.objects.rebuild()
        return super(NewCommentForm, self).save(*args, **kwargs)

class PostForm(forms.ModelForm):
    title = forms.CharField(label="Title",
                           widget=forms.TextInput(
                               attrs={
                                   "placeholder": "Title",
                                   "class": "form-control",
                               }
                           )
                           )
    excerpt = forms.CharField(label="Excerpt",
                           widget=forms.TextInput(
                               attrs={
                                   "placeholder": "Excerpt",
                                   "class": "form-control",
                               }
                           )
                           )
    content = forms.CharField(label="Content",
                           widget=forms.Textarea(
                               attrs={
                                   "placeholder": "Content",
                                   "class": "form-control",
                               }
                           )
                           )
    class Meta:
        model = Post
        fields = [
            'title',
            'excerpt',
            'content',
        ]

discussion/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Post, Comment
from .forms import NewCommentForm, PostForm
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.defaultfilters import slugify

def index(request):
    all_posts = Post.newmanager.all()
    return render(request, 'index.html', {'posts': all_posts})


def post_single(request, post):

    post = get_object_or_404(Post, slug=post, status='published')

    comments = post.comments.filter(status=True)

    user_comment = None

    if request.method == 'POST':
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.name = request.user.username
            user_comment.save()
            return HttpResponseRedirect('/discussion/' + post.slug)
    else:
        comment_form = NewCommentForm()
    return render(request, 'single.html', {'post': post, 'comments':  user_comment, 'comments': comments, 'comment_form': comment_form, 'user': request.user.username })

def new_post(request):
    form = PostForm(request.POST)
    if (form.is_valid() and request.method == 'POST'):
        post = Post()
        post.author = request.user.username
        post.title = form.cleaned_data['title']
        post.excerpt = form.cleaned_data['excerpt']
        post.content = form.cleaned_data['content']
        post.slug = slugify(post.title)
        post.save()
        return HttpResponseRedirect('/discussion/')
    context = {
        'form': form,
        'user': request.user.username
    }
    return render(request, 'newpost.html', context)

discussion/templates/index.html
{% extends 'home/base.html' %}
{% block content %}
<h1 style="text-align: center; margin-top: 100px;">Discussion Forum</h1>
    <div class="album py-5 bg-light" style="height: 100vh;">
      <div class="container">
        <div class="row" id="allpost">
          {% for post in posts %}
          <div class="col-md-4">
            <a class="text-dark" href="{{post.get_absolute_url}}">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="h4">{{post.title}}</p>
                  <p class="lead card-text">{{post.excerpt}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">{{post.author}}</small>
                  </div>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}

          {% if not request.user.is_authenticated %}
          <div class="container">
            <div class="row justify-content-center">
                <a class="btn btn-dark" href="{% url 'login:logging_in' %}" role="button">Login to create a new post</a>
            </div>
          </div>
          {% else %}
          <div class="container">
            <div class="row justify-content-center">
                <a class="btn btn-dark" href="newpost" role="button">Create new post</a>
            </div>
          </div>
          {% endif %} 

        </div>
      </div>
    </div>
<br>
    {% endblock %}

discussion/templates/newpost.html
{% extends 'home/base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>Create new post, as {{user}}</b></h2>
        <hr class="mt-0 mb-4">
        <form method='POST'>
            {% csrf_token %}
            {{ form.as_p }}
            <br>
           <button type="submit" class="btn btn-dark">Submit</button>
           <a class="btn btn-dark" href="../">Back</a>
        </form>
        <br>
      </div>
    </div>
  </div>
<br>

{% endblock %}

discussion/templates/single.html
{% extends 'home/base.html' %}
{% load humanize %}

{% block content %}

<style>
  @media screen and (min-width: 600px) {
    .children form {
      margin-left: -48px;
      /* will touch very left side */
    }

    .children .children form {
      margin-left: -96px;
      /* will touch very left side */
    }
  }
</style>

<br>
<br>

<div class="container">
  <div class="row justify-content-md-center pt-5">

    <div class="col-md-7">
      <p class="h2">{{post.title}}</p>
    </div>
    <div class="col-md-7">
      <p class="text-justify" style="font-size: 20px;">{{post.content|safe}}</p>
    </div>
    <div class="col-md-7">

      {% with allcomments.count as total_comments %}
      <h5 class="lead">
        {{ total_comments }} comment{{ total_comments|pluralize }}
      </h5>
      {% endwith %}

      {% load mptt_tags %}

      <div>
        {% recursetree comments %}
        <div id="{{ node.id }}" class="my-2 p-2 rounded">
          <div class="d-flex justify-content-between"><b>{{ node.name }}</b><div></div>{{ node.publish|naturaltime }}</div>
          <div>{{ node.content }}</div>
          <hr>
          {% if node.level < 3 %}
          {% if request.user.is_authenticated %}
          <button class="btn btn-light" onclick="myFunction({{ node.id }})">Reply</button>
          {% endif %}
          {% endif %}
        </div>
        {% if not node.is_leaf_node %}
        <div class="children pl-2 pl-md-5">
          {{ children }}
        </div>
        {% endif %}
        {% endrecursetree %}
      </div>

      {% if request.user.is_authenticated %}
      <button onclick="thatFunction()" class="btn btn-dark" id="newCommentButton">Create new comment</button>
      {% endif %}

      <div id="thatDIV" style="display:none;">
        <br>
        <p class="h6">Post comment as {{user}}</p>
        <form id="myForm" method="post">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-dark" >Submit</button>
        </form>
      </div>

    </div>
  </div>
</div>
<br>
<script>
$(document).ready(function(){
  $("#newCommentButton").click(function(){
    $("#thatDIV").slideToggle();
  });
});

  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {
    if (document.contains(document.getElementById("newForm"))) {
      document.getElementById("newForm").remove();
    }

    var d1 = document.getElementById(id);
    d1.insertAdjacentHTML('afterend',
      '<form id="newForm" class="form-insert py-2" method="post"> \
                <select name="parent" class="d-none" id="id_parentt"> \
                <option value="' + id + '" selected="' + id + '"></option> \
                </select> \
                <label for="id_content">Reply as {{user}}:</label> \
                <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content" placeholder="Content"></textarea> \
                {% csrf_token %} \
                <br> \
                <button type="submit" class="btn btn-dark">Submit</button> <button type="button" class="btn btn-dark" onclick="formExit()"">Close</button> \
              </form>');

    //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
  }

  $('#myForm').trigger("reset");
</script>

{% endblock %}